
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# 
# Triangle	 	
# Tn=n(n+1)/2	 	
# 1, 3, 6, 10, 15, ...
# 
# Pentagonal	 	
# Pn=n(3n−1)/2	 	
# 1, 5, 12, 22, 35, ...
# 
# Hexagonal	 	
# Hn=n(2n−1)	 	
# 1, 6, 15, 28, 45, ...
# 
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.

def triangle(n):
    return int(n * (n + 1) / 2)

def is_pentagonal(number):
    return (1 + (24 * number + 1) ** 0.5) % 6 == 0

def is_hexagonal(number):
    return (1 + (8 * number + 1) ** 0.5) % 4 == 0

def tri_pen_hex(nth):
    n = 2
    count = 0
    
    while True:
        number = triangle(n)
        
        if is_pentagonal(number) and is_hexagonal(number):
            count += 1
            if count == nth:
                return number
            else:
                n += 1
        else:
            n += 1

tri_pen_hex(2)