# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
# 
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# 
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

def triangulator(index):
    sum = 0
    for i in range(index + 1):
        sum += i
        
    return sum

def number_of_divs(number):
    divs = 1
    
    for i in range(2, int(number ** (1 / 2) + 1)):
        if number % i == 0:
            divs += 1
                
    return divs * 2

def high_div_tri_num(floor):
    
    n = 1
    
    while True:
        number = triangulator(n)
        
        if number_of_divs(number) > floor:
            break
        else:
            n += 1
        
    return number

high_div_tri_num(500)




