# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# 
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# 
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
# and D = |Pk − Pj| is minimised; what is the value of D?

def is_pentagonal(number):
    return (1 + (24 * number + 1) ** 0.5) % 6 == 0

def penta_vrsn(n):
    return int(n * (3 * n - 1) / 2)

def pentagonal_pair(nth):
    n = 1
    count = 0
    
    while True:
        for i in range(1, n):
            curr_penta = penta_vrsn(n)
            sub_penta = penta_vrsn(i)
            if is_pentagonal(curr_penta - sub_penta) and is_pentagonal(curr_penta + sub_penta):
                count += 1
                if count == nth:
                    return curr_penta, sub_penta, curr_penta - sub_penta
        else:
            n += 1

pentagonal_pair(1)